version: "3.7"
services:
  app:
    build: .
    command: sh -c "npm install;npx vite --host --https=false"
    working_dir: /home/node/app
    ports:
      - 8080:8080
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    env_file:
      - .env
